# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZMA8Ebod8JfoTM3PqjDL2hOP0TkuDcDt
"""

# pip install streamlit

import streamlit as st
import pandas as pd
import joblib

df = pd.read_csv('data/jobs.csv')

# rf = joblib.load('salary_predictor.pkl')
# title_encoder = joblib.load('title_encoder.pkl')
# company_encoder = joblib.load('company_encoder.pkl')
# category_encoder = joblib.load('category_encoder.pkl')
# state_encoder = joblib.load('state_encoder.pkl')
# county_encoder = joblib.load('county_encoder.pkl')

rf = joblib.load('models/salary_predictor.pkl')
title_encoder = joblib.load('models/title_encoder.pkl')
company_encoder = joblib.load('models/company_encoder.pkl')
category_encoder = joblib.load('models/category_encoder.pkl')
state_encoder = joblib.load('models/state_encoder.pkl')
county_encoder = joblib.load('models/county_encoder.pkl')

df = pd.read_csv('data/jobs.csv')

# title_dropdown = st.selectbox(
#     options=sorted(title_encoder.classes_),
#     label = 'Job title',
#     placeholder= 'Title:'
# )
# company_dropdown = st.selectbox(
#     options=sorted(company_encoder.classes_),
#     label = 'company',
#     placeholder= 'company'
# )

# category_dropdown = st.selectbox(
#     options=sorted(category_encoder.classes_),
#     label = 'category',
#     placeholder = 'category'
# )

# state_dropdown = st.selectbox(
#     options=sorted([x for x in state_encoder.classes_ if x is not None]),
#     label = 'state',
#     placeholder= 'State'
# )
# county_dropdown = st.selectbox(
#     options=[],
#     label = 'County',
#     placeholder= 'County:'

# )

company = st.selectbox(
    "Company",
    sorted(company_encoder.classes_)
)

filtered_titles = (
    df.loc[df["company"] == company, "title"]
      .dropna()
      .unique()
)

title = st.selectbox(
    "Title",
    sorted(filtered_titles)
)

filtered_states = (
    df.loc[df["company"] == company, "state"]
      .dropna()
      .unique()
)

state = st.selectbox(
    "State",
    sorted(filtered_states)
)

filtered_counties = (
    df.loc[df["state"] == state, "county"]
      .dropna()
      .unique()
)

county = st.selectbox(
    "County",
    sorted(filtered_counties)
)


filtered_categories = (
    df.loc[
        (df["company"] == company) &
        (df["title"] == title),
        "category"
    ]
    .dropna()
    .unique()
)

category = st.selectbox(
    "Category",
    sorted(filtered_categories)
)

# # Display selections
st.write("Company:", company)
st.write("Title:", title)
st.write("State:", state)
st.write("County:", county)
st.write("Category:", category)


if st.button("Predict Salary"):

    # Encode the selected values
    title_encoded = title_encoder.transform([title])[0]
    company_encoded = company_encoder.transform([company])[0]
    category_encoded = category_encoder.transform([category])[0]
    state_encoded = state_encoder.transform([state])[0]
    county_encoded = county_encoder.transform([county])[0]

    # Create input for the model
    new_job = pd.DataFrame({
        "title": [title_encoded],
        "company": [company_encoded],
        "category": [category_encoded],
        "state": [state_encoded],
        "county": [county_encoded]
    })

    # Predict salary
    predicted_salary = rf.predict(new_job)[0]

    # Display result
    st.success(f"Predicted Salary: £{predicted_salary:,.0f}")





