# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZMA8Ebod8JfoTM3PqjDL2hOP0TkuDcDt
"""

# pip install streamlit

import streamlit as st
import pandas as pd
import joblib

raw_df = pd.read_csv('data/jobs.csv')

# rf = joblib.load('salary_predictor.pkl')
# title_encoder = joblib.load('title_encoder.pkl')
# company_encoder = joblib.load('company_encoder.pkl')
# category_encoder = joblib.load('category_encoder.pkl')
# state_encoder = joblib.load('state_encoder.pkl')
# county_encoder = joblib.load('county_encoder.pkl')

rf = joblib.load('models/salary_predictor.pkl')
title_encoder = joblib.load('models/title_encoder.pkl')
company_encoder = joblib.load('models/company_encoder.pkl')
category_encoder = joblib.load('models/category_encoder.pkl')
state_encoder = joblib.load('models/state_encoder.pkl')
county_encoder = joblib.load('models/county_encoder.pkl')

df = pd.read_csv('data/jobs.csv')

title_dropdown = st.selectbox(
    options=sorted(title_encoder.classes_),
    label = 'Job title',
    placeholder= 'Title:'
)
company_dropdown = st.selectbox(
    options=sorted(company_encoder.classes_),
    label = 'company',
    placeholder= 'company'
)

category_dropdown = st.selectbox(
    options=sorted(category_encoder.classes_),
    label = 'category',
    placeholder = 'category'
)

state_dropdown = st.selectbox(
    options=sorted([x for x in state_encoder.classes_ if x is not None]),
    label = 'state',
    placeholder= 'State'
)
county_dropdown = st.selectbox(
    options=[],
    label = 'County',
    placeholder= 'County:'

)

company = st.selectbox(
    "Company",
    sorted(company_encoder.classes_)
)

filtered_titles = (
    raw_df.loc[raw_df["company"] == company, "title"]
      .dropna()
      .unique()
)

title = st.selectbox(
    "Title",
    sorted(filtered_titles)
)

state = st.selectbox(
    "State",
    sorted(raw_df["state"].dropna().unique())
)

filtered_counties = (
    raw_df.loc[raw_df["state"] == state, "county"]
      .dropna()
      .unique()
)

county = st.selectbox(
    "County",
    sorted(filtered_counties)
)


filtered_categories = (
    df.loc[
        (raw_df["company"] == company) &
        (raw_df["title"] == title),
        "category"
    ]
    .dropna()
    .unique()
)

category = st.selectbox(
    "Category",
    sorted(filtered_categories)
)

# Display selections
st.write("Company:", company)
st.write("Title:", title)
st.write("State:", state)
st.write("County:", county)
st.write("Category:", category)

st.write(raw_df.columns)

st.write(raw_df[["state", "county"]].head(20))

st.write(raw_df["state"].dtype)
st.write(raw_df["county"].dtype)

st.write(raw_df["state"].nunique())
st.write(raw_df["county"].nunique())

st.write(state)
st.write(raw_df[raw_df["state"] == state].shape)

# title_val = title_encoder.transform([title_dropdown.value])[0]
# company_val = company_encoder.transform([company_dropdown.value])[0]
# category_val = category_encoder.transform([category_dropdown.value])[0]
# state_val = state_encoder.transform([state_dropdown.value])[0]
# county_val = county_encoder.transform([county_dropdown.value])[0]

# new_job = [[
#     title_val,
#     company_val,
#     category_val,
#     state_val,
#     county_val,
# ]]

# predicted_salary = rf.predict(new_job)[0]
# print(f"Predicted Salary: £{predicted_salary:,.0f}")





