# -*- coding: utf-8 -*-
"""Copy of Job market analysis project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qk4z4CR6rUUSAjDTbWv0GP-7sUvjJflz

Organizations and job seekers lack a centralized, data-driven view of labor market trends, making it difficult to identify in-demand skills, salary expectations, and emerging opportunities.

**Objective 1: Salary Intelligence**
Questions to answer
Which job titles pay the highest salaries?
Which job categories pay the most?
What is the salary distribution across roles?
What are the salary ranges for different positions?
Insights

Examples:

Data Scientists earn more than Data Analysts.
Software Engineers have wider salary ranges.
Some categories show higher salary variability.

This is likely your strongest objective because salary data is available.

**Objective 2: Geographic Opportunity Analysis**
Questions
Which locations have the most openings?
Which locations offer the highest salaries?
Which regions specialize in certain job categories?
Insights

Examples:

London has more Data Analyst jobs.
Manchester offers competitive salaries in specific categories.
Some locations have many openings but lower pay.
Objective 3: Employer Hiring Analysis
Questions
Which companies post the most jobs?
Which companies offer the highest salaries?
Which categories are most common for each employer?
Insights

Examples:

Certain employers dominate hiring.
Some employers consistently advertise higher salary ranges.
Objective 4: Category Demand Analysis
Questions
Which job categories have the most openings?
Which categories pay the highest salaries?
Which categories show the largest salary spread?
Insights

Examples:

IT Jobs may have the highest volume.
Engineering roles may have higher median salaries.
Objective 5: Job Title Analysis
Questions
Most common job titles?
Highest-paying job titles?
Salary variation within the same title?
Insights

Examples:

Senior roles command significantly higher salaries.
Some titles have large salary variability.
"""

import requests
import pandas as pd
import json
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import userdata
job_key=userdata.get('job_key')
job_app_id=userdata.get('job_app_id')

# @title
def fetch_job_listings(app_id: str, app_key: str,
                       search_query: str,
                       #location :str ,
                       start_page_number :int = 1,
                       end_page_number : int =20 ,
                       country: str = 'us') -> dict:
    all_responses = []
    for page in range(start_page_number, end_page_number+1):
      base_url = f"https://api.adzuna.com/v1/api/jobs/{country}/search/{page}"
      parameters = {
        'app_id': app_id,
        'app_key': app_key,
        'what': search_query,
        #'where': location,
        'content-type': 'application/json'
      }
      response = requests.get(base_url, params=parameters)
      if response.status_code == 200:
          data = response.json()
          all_responses.extend(data.get('results', []))
    return all_responses

# @title
import json

def parse_response(response: dict):
    if 'results' in response:
        for job in response['results']:
            job_title = job.get('title', 'N/A')
            company = job.get('company', {}).get('display_name', 'N/A')
            #location = job.get('location', {}).get('display_name', 'N/A')
            print(f"Job Title: {job_title}, Company: {company}")
    else:
        print("No results found or an error occurred.")

# @title
app_id = job_app_id
app_key = job_key
search_query = 'Software'
#location = 'new york'


job_listing_response_data = fetch_job_listings(app_id, app_key,search_query,end_page_number = 100)
parse_response(job_listing_response_data)
#job_listing_response_data

job_listing_response_data

# @title
# # @title
# def fetch_all_categories(app_id : str, app_key : str , country : str = 'us') -> dict :
#   base_url=f"https://api.adzuna.com/v1/api/jobs/{country}/categories"
#   parameters = {
#       "app_id" : app_id,
#       "app_key" : app_key,
#       "content-type": 'application/json'
#   }
#   response = requests.get(base_url,params=parameters)
#   return response.json()

# @title
# # @title
# def parse_response(response:dict):
#   if 'results' in response:
#     for job in response['results']:
#       job_category= job.get('label', 'N/A')
#       print(f"Category: {job_category}")
#     else:
#       print("No results found")

# @title
# # @title
# app_id=job_app_id
# api_key=job_key
# response_data= fetch_all_categories(app_id, api_key)
# parse_response(response_data)

job_listing_response_data
df= pd.json_normalize(job_listing_response_data)

#raw_df = df.copy()
model_df = df.copy()

df.info()

df.columns

#job_listing_response_data
df.head(1)

df = df.drop(columns = ['id' , 'description' ,'adref','redirect_url','redirect_url','__CLASS__',
                        'company.__CLASS__','location.__CLASS__',
                        'category.__CLASS__','category.tag'])
df.head(10)

df.columns

df.isnull().sum()

df = df.drop(columns = ['contract_time' , 'contract_type','latitude' ,'salary_is_predicted',
                        'location.display_name','longitude','created'])
df.head()

df['salary_max']= df['salary_max'].fillna(df['salary_min'])

df[df.isna().any(axis=1)]

df['salary'] =(df['salary_max'] + df['salary_min'])/2

df=df.drop(columns = ['salary_max','salary_min'])

df.head(1)

df_salary_by_title = df.groupby('title')['salary'].mean()

df_salary_by_title= df_salary_by_title.to_frame()

df_salary_by_title.reset_index()

df_salary_by_title= df_salary_by_title.sort_values(by='salary',ascending = False)

# #Job categories which pay the most
# df_salary_by_category = df[['category.label','salary']]
# df_salary_by_category= df_salary_by_category.groupby('category.label')['salary'].mean()
# df_salary_by_category

# df_salary_by_category= df_salary_by_category.to_frame()
# df_salary_by_category.reset_index()
# df_salary_by_category = df_salary_by_category.sort_values(by='salary',ascending= False)
# df_salary_by_category = df_salary_by_category.head(10)
# df_salary_by_category

sns.barplot(data=df_salary_by_title.head(10) ,x='salary', y ="title", orient="h")
plt.show()

df_salary_by_title = df_salary_by_title.reset_index()

#Remove common separators like hyphen commas and /
df[['title' ,'description']] = df['title'].str.split(r'/|,', expand =True,n=1)

df['title']= df['title'].str.strip('()')
df['title']= df['title'].str.replace(r'\(|\)', '', regex=True)

df.rename(columns = {'category.label':'category','location.area':'location' , 'company.display_name':'company'} ,inplace= True)

df["location"] = df["location"].str.join(", ")

df=df.drop(columns = ['description'])
df.head(10)

df[['country' , 'state' , 'county','town']] = df['location'].str.split(r',',expand =True,n=3)

df= df.drop(columns = ['country','location'])
df.head(1)

df.head(1)

raw_df = df.copy()

from sklearn.preprocessing import LabelEncoder

c=df.columns.to_list()

c

title_encoder = LabelEncoder()
company_encoder = LabelEncoder()
category_encoder = LabelEncoder()
state_encoder = LabelEncoder()
county_encoder = LabelEncoder()
town_encoder = LabelEncoder()

df['title'] = title_encoder.fit_transform(df['title'])
df['company'] = company_encoder.fit_transform(df['company'])
df['category'] = category_encoder.fit_transform(df['category'])
df['state'] = state_encoder.fit_transform(df['state'])
df['county'] = county_encoder.fit_transform(df['county'])
df['town'] = town_encoder.fit_transform(df['town'])

x = df.drop(columns = ['salary'])
x.head(1)

x1=df.drop(columns = ['town','salary'])

y=df['salary']
y.head(1)

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x1,y,test_size=0.25)

lr= LinearRegression()
lr.fit(x_train,y_train)

y_pred = lr.predict(x_test)

from sklearn.metrics import r2_score , confusion_matrix , mean_absolute_error , root_mean_squared_error
r2_score(y_test,y_pred)

from sklearn.ensemble import RandomForestRegressor

rf= RandomForestRegressor()
rf.fit(x_train,y_train)

y_pred = rf.predict(x_test)

print("R2 score :",r2_score(y_test,y_pred))
print("RMSE :", root_mean_squared_error(y_test,y_pred))
print("MAE  :" ,mean_absolute_error(y_test,y_pred))

state_encoder.classes_

import ipywidgets as widgets
from IPython.display import display

# Create dropdowns from unique values in each column
title_dropdown = widgets.Dropdown(
    options=sorted(title_encoder.classes_),
    description='Title:'
)

company_dropdown = widgets.Dropdown(
    options=sorted(company_encoder.classes_),
    description='Company:'
)

category_dropdown = widgets.Dropdown(
    options=sorted(category_encoder.classes_),
    description='Category:'
)

state_dropdown = widgets.Dropdown(
    options=sorted([x for x in state_encoder.classes_ if x is not None]),
    description='State:'
)

# county_dropdown = widgets.Dropdown(
#     options=sorted([x for x in county_encoder.classes_ if x is not None]),
#     description='County:'
# )
county_dropdown = widgets.Dropdown(
    options=[],
    description='County:'
)


# display(
#     title_dropdown,
#     company_dropdown,
#     category_dropdown,
#     state_dropdown,
#     county_dropdown,
# )

def update_counties(change):
    selected_state = change['new']

    counties = (
        raw_df.loc[
            raw_df['state'] == selected_state,
            'county'
        ]
        .dropna()
        .unique()
    )

    county_dropdown.options = sorted(counties)

state_dropdown.observe(update_counties, names='value')

def update_titles(change):
    selected_company = change['new']

    title = (
        raw_df.loc[
            raw_df['company'] == selected_company,
            'title'
        ]
        .dropna()
        .unique()
    )

    title_dropdown.options = sorted(title)

company_dropdown.observe(update_titles, names='value')

def update_category(change):
    selected_title = change['new']

    category = (
        raw_df.loc[
            raw_df['title'] == selected_title,
            'category'
        ]
        .dropna()
        .unique()
    )

    category_dropdown.options = sorted(category)

title_dropdown.observe(update_category, names='value')

display(company_dropdown, title_dropdown , category_dropdown)
display(state_dropdown, county_dropdown)

title_val = title_encoder.transform([title_dropdown.value])[0]
company_val = company_encoder.transform([company_dropdown.value])[0]
category_val = category_encoder.transform([category_dropdown.value])[0]
state_val = state_encoder.transform([state_dropdown.value])[0]
county_val = county_encoder.transform([county_dropdown.value])[0]

new_job = [[
    title_val,
    company_val,
    category_val,
    state_val,
    county_val,
]]

predicted_salary = rf.predict(new_job)[0]
print(f"Predicted Salary: £{predicted_salary:,.0f}")

import joblib
joblib.dump(rf , 'salary_predictor.pkl')

joblib.dump(title_encoder, 'title_encoder.pkl')
joblib.dump(company_encoder, 'company_encoder.pkl')
joblib.dump(category_encoder, 'category_encoder.pkl')
joblib.dump(state_encoder, 'state_encoder.pkl')
joblib.dump(county_encoder, 'county_encoder.pkl')

rf = joblib.load('salary_predictor.pkl')

title_encoder = joblib.load('title_encoder.pkl')
company_encoder = joblib.load('company_encoder.pkl')
category_encoder = joblib.load('category_encoder.pkl')
state_encoder = joblib.load('state_encoder.pkl')
county_encoder = joblib.load('county_encoder.pkl')